### PR TITLE
Dependency Upgrades

### PR DESCRIPTION
**Pull request by jwchang0206**
Mubsub 0.0.2 -> 0.2.0

Underscore 1.3.3 > 1.4.4

### CODE REVIEW

**Comment by kof** [comment]
Hi, thanks for the pull, I need some time to investigate if everything is fine. Are tests still running?

**Comment by kof** [comment]
Did you tried benchs? How high is the CPU load?

**Comment by jwchang0206** [comment]
**mongo pubsub** (mubsub API changed)
N/A

**redis pubsub** 
3674ms

**mongo storage**
5992ms

**redis storage**
5788ms

And the test could not be run properly.

Probably because test is written for `mubsub` 0.0.2.

**Comment by kof** [comment]
what does it mean mongo pubsub N/A?

do you want to ensure tests are running?

Also did you verified all mubsub api fn calls still work? I am not sure that everything is tested.

**Comment by jwchang0206** [comment]
Mongo Pubsub prints log at console but stops I do not why.

Would you look at code?

I'm using this code with my project (using socket.io a lot)

and having no problems for now :)

**Comment by kof** [comment]
you mean if you run tests? ok, will take a look.

How much connections per hour or users does your project have?

**Comment by jwchang0206** [comment]
my project is still in development

**Comment by orangenotorange** [comment]
I have finished a dependency upgrade for this project. I have posted it as a new package instead of a fork for no particular reason so if you want to merge that's fine with me.  I have all of your unit tests and benchmarks working with this project.  

https://github.com/tmfkmoney/mong.socket.io

**Comment by kof** [comment]
I will build a mongo store for engine.io soon. Probably I will revisit this store first and make it working. For those who is still on the old socket.io version. However I am not sure I want to support it and people just should use the new socket.io with engine.io inside.

**Pull request closed without merging**
